<?php
$template_img_navbar = '
<div style="padding-top: 20px;">
  <a href="{THUMB_TGT}">'.THUMB_TITLE.'</a>
  &nbsp;|&nbsp;
  <a href="{SLIDESHOW_TGT}">'.SLIDESHOW_TITLE.'</a>
  &nbsp;|&nbsp;
  <a href="{ECARD_TGT}">'.ECARD_TITLE.'</a>
  <span class="float_right">
    <a href="{PREV_TGT}">&laquo; '.PREV_TITLE.'</a>
    &nbsp;|&nbsp;
    <a href="{NEXT_TGT}">'.NEXT_TITLE.' &raquo;</a>
  </span>
</div>
';
?>
